<a href="https://colab.research.google.com/github/aqilaqsa/Artificial-Intelligence/blob/main/TA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

In [ ]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

aqilaaqsa_combined_data_5304_path = kagglehub.dataset_download('aqilaaqsa/combined-data-5304')
aqilaaqsa_training_path = kagglehub.dataset_download('aqilaaqsa/training')
aqilaaqsa_5000_values_deepl_path = kagglehub.dataset_download('aqilaaqsa/5000-values-deepl')
aqilaaqsa_embarrassment_label_path = kagglehub.dataset_download('aqilaaqsa/embarrassment-label')
aqilaaqsa_train_embarrassment_label_path = kagglehub.dataset_download('aqilaaqsa/train-embarrassment-label')
aqilaaqsa_relevant_labels_4_path = kagglehub.dataset_download('aqilaaqsa/relevant-labels-4')
aqilaaqsa_translated_5000_deepl_path = kagglehub.dataset_download('aqilaaqsa/translated-5000-deepl')
aqilaaqsa_5000_with_labels_placeholder_path = kagglehub.dataset_download('aqilaaqsa/5000-with-labels-placeholder')
aqilaaqsa_for_label_mapping_path = kagglehub.dataset_download('aqilaaqsa/for-label-mapping')
aqilaaqsa_embarrassment_and_envy_labels_path = kagglehub.dataset_download('aqilaaqsa/embarrassment-and-envy-labels')
aqilaaqsa_last_i_hope_path = kagglehub.dataset_download('aqilaaqsa/last-i-hope')
aqilaaqsa_lastplz_path = kagglehub.dataset_download('aqilaaqsa/lastplz')
aqilaaqsa_add_random_id_path = kagglehub.dataset_download('aqilaaqsa/add-random-id')

print('Data source import complete.')

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore")

In [ ]:
df_train = pd.read_csv('/kaggle/input/training/training.csv')

In [ ]:
# prompt: shape

df_train.shape

In [ ]:
df_train.head(800)

In [ ]:
# prompt: drop columns other than text and label

df_train = df_train[['text', 'label']]

In [ ]:
# prompt: drop label containing "2"

df_train = df_train[~df_train['label'].astype(str).str.contains('2')]

In [ ]:
# prompt: drop label containing 5

df_train = df_train[~df_train['label'].astype(str).str.contains('5')]

In [ ]:
# prompt: see the df trainshape

df_train.shape

In [ ]:
df_train.info()

In [ ]:
# prompt: install google trans

!pip install googletrans==4.0.0-rc1

In [ ]:
# prompt: gimme head

df_train.head()

In [ ]:
# prompt: install deepl

!pip install deepl

In [ ]:
# prompt: gimme the csv from df_train called relevantlabels

df_train.to_csv('relevantlabels.csv', index=False)

In [ ]:
# prompt: read relevantlabels.csv

import pandas as pd

relevantlabels = pd.read_csv('/kaggle/input/relevant-labels-4/relevantlabels (1).csv')
relevantlabels

In [ ]:
# prompt: translate relevantlabels text to bahasa indonesia using deepl, first 5000 lines, give logs? or smth so i can see the progress, put in new df called df_translateddeepl

import pandas as pd
import deepl
import time

# Assuming you have your DeepL API key set as an environment variable
# or replace with your actual key
try:
    translator = deepl.Translator("69b04546-c630-4dba-9227-bcca78ba8444:fx")
except deepl.exceptions.DeepLException as e:
    print(f"DeepL API error: {e}")
    print("Please ensure your API key is correct and set.")
    exit()

relevantlabels = pd.read_csv('relevantlabels (1).csv')
df_translateddeepl = pd.DataFrame(columns=['text', 'label'])

# Process first 5000 lines or the length of the DataFrame, whichever is smaller
num_lines = min(5000, len(relevantlabels))

for i in range(num_lines):
    try:
      original_text = relevantlabels['text'][i]
      result = translator.translate_text(original_text, target_lang="ID")
      translated_text = result.text
      df_translateddeepl = pd.concat([df_translateddeepl, pd.DataFrame({'text': [translated_text], 'label': [relevantlabels['label'][i]]})], ignore_index=True)
      # Add a delay to prevent hitting the API rate limit (adjust as needed)
      time.sleep(0.1)
      # Print progress
      if i % 100 == 0:
        print(f"Processed {i} lines...")
    except Exception as e:
      print(f"Error translating line {i}: {e}")
      # Handle the error, skip the line or log it appropriately.
      continue

print("Translation complete.")

#Now you have df_translateddeepl
print(df_translateddeepl.head())

In [ ]:
# # prompt: translate relevantlabels text to bahasa indonesia, first 5000 lines, give logs? or smth so i can see the progress, put in new df called df_translated

# from googletrans import Translator
# translator = Translator()

# # Initialize an empty list to store the translated texts
# translated_texts = []

# # Iterate through the first 5000 rows of the DataFrame
# for i in range(min(5000, len(relevantlabels))):
#     try:
#         # Translate the text in the 'text' column to Indonesian
#         translated = translator.translate(relevantlabels['text'][i], dest='id')
#         translated_texts.append(translated.text)
#         # Print progress every 100 translations
#         if (i + 1) % 100 == 0:
#             print(f"Translated {i + 1} texts")
#     except Exception as e:
#         print(f"Error translating text at index {i}: {e}")
#         translated_texts.append(relevantlabels['text'][i])  # Keep original text if translation fails

# # Create a new DataFrame with the translated texts
# df_translated = pd.DataFrame({'text': translated_texts})
# # Add the 'label' column to the new DataFrame
# df_translated['label'] = relevantlabels['label'][:len(translated_texts)]

# print("Translation complete.")

In [ ]:
# # prompt: translate df_train text to bahasa indonesia, first 5000 lines, give logs? or smth so i can see the progress, put in new df called df_translated

# from googletrans import Translator
# translator = Translator()
# import pandas as pd

# df_translated = pd.DataFrame(columns=['translated_text'])

# for i in range(min(5000, len(df_train))):
#     try:
#         translation = translator.translate(df_train['text'][i], dest='id')
#         df_translated.loc[i] = translation.text
#         if i % 100 == 0:
#           print(f"Translated {i} lines")
#     except Exception as e:
#         print(f"Error translating line {i}: {e}")
#         df_translated.loc[i] = '' # or some other default value

# print("Translation complete.")

In [ ]:
# prompt: head

df_translateddeepl.head(800)

In [ ]:
# prompt: gimme the csv

df_translateddeepl.to_csv('translated_textdeepl.csv', index=False)

In [ ]:

df_translateddeepl = pd.read_csv('/kaggle/input/translated-5000-deepl/translated_textdeepl.csv')

In [ ]:

df_translateddeepl.info()

In [ ]:

# Assuming 'Feelio_Dataset_Sentiment_5000.csv' is the correct filename
try:
    df_traincurateddeepl = pd.read_csv('/kaggle/input/5000-with-labels-placeholder/Feelio_Dataset_Sentiment_5000deepl.csv')
except FileNotFoundError:
    print("Error: 'Feelio_Dataset_Sentiment_5000deepl.csv' not found.")
    exit() # Exit the script if file not found

In [ ]:
    df_traincurateddeepl.info()

In [ ]:
import pandas as pd

relevantlabels = pd.read_csv('/kaggle/input/relevant-labels-4/relevantlabels (1).csv')
relevantlabels

In [ ]:
# prompt: read relevantlabels.csv then map 0 with sedih, map 1 with senang, map 3 with marah, and map 4 with takut

label_mapping = {0: 'sedih', 1: 'senang', 3: 'marah', 4: 'takut'}
relevantlabels['label_name'] = relevantlabels['label'].map(label_mapping)
relevantlabels

In [ ]:

df_traincurateddeepl.info()

In [ ]:
# prompt: cocokkan relevantlabels dan isi label df_trainingcurated sesuai urutannya. jika relevantlabels mengandung senang, berikan 1 jika tidak berikan 0 pada kolom senang di df_traincurated dan lainnya juga sedih takut marah (boolean). pastikan bentuk akhir df_traincurated yaitu "ID", "Teks", "Senang", "Sedih", "Marah", "Iri", "Malu, "Takut". kapitalisasi tidak penting.

import pandas as pd

# Assuming df_traincurated and relevantlabels are already defined as in your previous code

# Create new boolean columns for emotions in df_traincurated
df_traincurateddeepl['Senang'] = 0
df_traincurateddeepl['Sedih'] = 0
df_traincurateddeepl['Marah'] = 0
df_traincurateddeepl['Iri'] = 0
df_traincurateddeepl['Malu'] = 0
df_traincurateddeepl['Takut'] = 0

# Function to check for emotion and set corresponding column
def set_emotion_columns(row):
    text = str(row['Teks']).lower()  # Convert to lowercase for case-insensitive matching
    labels = str(row['relevant_labels']).lower().split(',')  # Assuming comma-separated labels

    if 'senang' in labels:
        row['Senang'] = 1
    if 'sedih' in labels:
        row['Sedih'] = 1
    if 'marah' in labels:
        row['Marah'] = 1
    if 'takut' in labels:
        row['Takut'] = 1

    return row

# Assuming 'relevant_labels' column in df_traincurated corresponds to the 'label' in relevantlabels
# Replace 'label' with the actual column name in df_traincurated if different.
# The below assumes that relevantlabels and df_traincurated have the same length
df_traincurateddeepl['relevant_labels'] = relevantlabels['label_name']
df_traincurateddeepl = df_traincurateddeepl.apply(set_emotion_columns, axis=1)

# Drop the temporary 'relevant_labels' column if needed.
df_traincurateddeepl = df_traincurateddeepl.drop(columns=['relevant_labels'])

# Reorder columns
df_traincurateddeepl = df_traincurateddeepl[['ID', 'Teks', 'Senang', 'Sedih', 'Marah', 'Iri', 'Malu', 'Takut']]

df_traincurateddeepl.head(5000)

In [ ]:
# prompt: berikan saya bentuk csv baru

df_traincurateddeepl.to_csv('new_sentiment_data_5000deepl.csv', index=False)

In [ ]:
# prompt: read new_sentiment_data_5000deepl.csv

df_traincurateddeepl = pd.read_csv('/kaggle/input/for-label-mapping/new_sentiment_data_5000deepl.csv')
print(df_traincurateddeepl.head())

In [ ]:
# prompt: df head all

df_traincurateddeepl.head(5001)

In [ ]:
# prompt: count values of each column

# Assuming df_traincurated is already defined as in your previous code

# Count values in each column
for column in df_traincurateddeepl.columns:
    print(f"Value counts for column '{column}':")
    print(df_traincurateddeepl[column].value_counts())
    print("-" * 20)

In [ ]:
# prompt: gimme the csv

df_traincurateddeepl.to_csv('/kaggle/working/5000finaldeepl.csv', index=False)

In [ ]:
import pandas as pd

final5304 = pd.read_csv('/kaggle/input/5000-values-deepl/5000finaldeepl.csv')
final5304.info()

In [ ]:
# prompt: read train_fearjealousy.tsv and then convert to csv

import pandas as pd

# Assuming 'train_fearjealousy.tsv' is in the current directory
try:
    df = pd.read_csv('train_fearjealousy.tsv', sep='\t')  # Specify the separator as tab
except FileNotFoundError:
    print("Error: 'train_fearjealousy.tsv' not found.")
    exit()

# Convert the DataFrame to CSV
df.to_csv('train_fearjealousy.csv', index=False)  # index=False prevents writing row indices
print("Conversion complete. File saved as 'train_fearjealousy.csv'")

In [ ]:
df.info()

In [ ]:
df.head(800)

In [ ]:
# prompt: drop eebbqej column

# Assuming df_traincurateddeepl is your DataFrame
# and you want to drop a column named 'eebbqej'

if 'eebbqej' in df.columns:
    df = df.drop(columns=['eebbqej'])
    print("Column 'eebbqej' dropped successfully.")
else:
    print("Column 'eebbqej' not found in the DataFrame.")

In [ ]:
df.head()

In [ ]:
# prompt: give each column a title, "text" and "label" put on the first row as header

df = df.rename(columns={
      df.columns[0]: "text",
      df.columns[1]: "label"
    })

    # Save the updated DataFrame with the new header
df.to_csv('trainembarrassment.csv', index=False)

print("Header added successfully.")

In [ ]:
df.head()

In [ ]:
# prompt: drop rows that does not contain "12" in label

#Drop rows that does not contain "12" in label
df = df[df['label'].astype(str).str.contains('12')]

In [ ]:
df.info()

In [ ]:
df.head(303)

In [ ]:
# prompt: make it into a csv called embarrassment data

import pandas as pd

# Assuming df is already defined as in your previous code
# and contains the data you want to save as a CSV

# Save the DataFrame to a CSV file named 'embarrassment_data.csv'
df.to_csv('embarrassment_data.csv', index=False)

print("DataFrame saved to 'embarrassment_data.csv'")

In [ ]:
df.info()

In [ ]:
df.head()

In [ ]:
# prompt: turn embarrassment_data_id.csv to utf-8

import pandas as pd

# Read the CSV file, specifying the encoding
try:
    df = pd.read_csv('embarrassment_data.csv', encoding='latin-1') # or 'iso-8859-1' or other encodings
except FileNotFoundError:
    print("Error: 'embarrassment_data.csv' not found.")
    exit()
except Exception as e:
    print(f"An error occurred while reading the file: {e}")
    exit()


# Save the DataFrame to a new CSV file with UTF-8 encoding
try:
    df.to_csv('embarrassment_data_id.csv', encoding='utf-8', index=False)
    print("File saved successfully as 'embarrassment_data_id.csv' with UTF-8 encoding.")
except Exception as e:
    print(f"An error occurred while saving the file: {e}")

In [ ]:
# prompt: read embarrassment_data_id.csv as df_id

df_id = pd.read_csv('embarrassment_data_id.csv')

In [ ]:
# prompt: head

df_id.head(303)

In [ ]:
# prompt: make a duplicate of 5000finaldeepl.csv named trialemid

import pandas as pd

# Load the original DataFrame
try:
    df_original = pd.read_csv('/kaggle/input/5000-values-deepl/5000finaldeepl.csv')
except FileNotFoundError:
    print("Error: '5000finaldeepl.csv' not found.")
    exit()

# Create a copy of the DataFrame
df_trialemid = df_original.copy()

# Save the copy to a new CSV file
df_trialemid.to_csv('/kaggle/working/trialemid.csv', index=False)

print("Duplicate file 'trialemid.csv' created successfully.")

In [ ]:
# prompt: read trialemid.csv

import pandas as pd

df_trialemid = pd.read_csv('trialemid.csv')
df_trialemid.info()

In [ ]:
# prompt: grab text values from embarrassment_data_id.csv and ADD on to the already existing Teks values from trialemid.csv, jangan hilangkan kolom lainnya, total teks adalah 5303 (header mengikuti header milik trialemid.csv)

import pandas as pd

# Load the two dataframes
try:
    df_trialemid = pd.read_csv('trialemid.csv')
    df_embarrassment = pd.read_csv('embarrassment_data_id.csv')
except FileNotFoundError:
    print("Error: One or both of the CSV files not found.")
    exit()

# Concatenate the 'Teks' columns, ensuring the other columns are preserved
# Assuming 'text' column in df_embarrassment maps to 'Teks' in df_trialemid
df_combined = pd.concat([df_trialemid, df_embarrassment[['text']]], ignore_index=True)


#Rename text column to Teks
df_combined = df_combined.rename(columns={'text':'Teks'})

# Fill NaN values in 'Teks' column with empty strings
df_combined['Teks'] = df_combined['Teks'].fillna('')

#Save combined dataframe
df_combined.to_csv('combined_data.csv', index=False)
print("Combined dataframe saved to 'combined_data.csv'")
print(f"Total rows: {len(df_combined)}")

In [ ]:
# Display the resulting dataframe
df_combined = pd.read_csv('/kaggle/input/combined-data-5304/combined_data.csv')
df_combined.info()

In [ ]:
df_combined.head(5303)

In [ ]:
df_combined.info()

In [ ]:
# prompt: drop "Tekz"

# Assuming df_combined is already defined as in your previous code

# Check if the column exists before dropping
if 'Tekz' in df_combined.columns:
    df_combined = df_combined.drop(columns=['Tekz'])
    print("Column 'Tekz' dropped successfully.")
    #Save combined dataframe
    df_combined.to_csv('combined_data.csv', index=False)
    print("Combined dataframe saved to 'combined_data.csv'")
else:
    print("Column 'Tekz' not found in the DataFrame.")

In [ ]:
df_combined.head(5304)

In [ ]:
# prompt:  in df_combined NaN values, give "1" under column "Malu" and "0" under column "Senang", "Sedih", "Marah", "Iri", "Takut"

# Assuming df_combined is already defined and loaded as in your previous code.

# Fill NaN values in specified columns
df_combined['Malu'] = df_combined['Malu'].fillna(1)
df_combined['Senang'] = df_combined['Senang'].fillna(0)
df_combined['Sedih'] = df_combined['Sedih'].fillna(0)
df_combined['Marah'] = df_combined['Marah'].fillna(0)
df_combined['Iri'] = df_combined['Iri'].fillna(0)
df_combined['Takut'] = df_combined['Takut'].fillna(0)

# Convert columns to integer type if needed
df_combined['Malu'] = df_combined['Malu'].astype(int)
df_combined['Senang'] = df_combined['Senang'].astype(int)
df_combined['Sedih'] = df_combined['Sedih'].astype(int)
df_combined['Marah'] = df_combined['Marah'].astype(int)
df_combined['Iri'] = df_combined['Iri'].astype(int)
df_combined['Takut'] = df_combined['Takut'].astype(int)

#Save the updated DataFrame
df_combined.to_csv('combined_data.csv', index=False)
print("Combined dataframe saved to 'combined_data.csv'")

df_combined.head(5304)

In [ ]:
df_combined.to_csv('final_combined_data.csv', index=False) #Saving to a new file
print("Combined dataframe saved to 'final_combined_data.csv'")

In [ ]:
# prompt: use deepl to translate dataframe named "embarrassment_data.csv" to bahasa indonesia

import pandas as pd
import deepl
import time

# Assuming you have your DeepL API key set as an environment variable
# or replace with your actual key
try:
    translator = deepl.Translator("41743afb-058e-4c43-adf3-abbd6abd3073:fx")
except deepl.exceptions.DeepLException as e:
    print(f"DeepL API error: {e}")
    print("Please ensure your API key is correct and set.")
    exit()

try:
    df = pd.read_csv('embarrassment_data.csv')
except FileNotFoundError:
    print("Error: 'embarrassment_data.csv' not found.")
    exit()

df_translated = pd.DataFrame(columns=['text', 'label'])

# Process all lines in the DataFrame
for i in range(len(df)):
    try:
        original_text = df['text'][i]
        result = translator.translate_text(original_text, target_lang="ID")
        translated_text = result.text
        df_translated = pd.concat([df_translated, pd.DataFrame({'text': [translated_text], 'label': [df['label'][i]]})], ignore_index=True)
        # Add a delay to prevent hitting the API rate limit (adjust as needed)
        time.sleep(0.1)
        # Print progress
        if i % 100 == 0:
            print(f"Processed {i} lines...")
    except Exception as e:
        print(f"Error translating line {i}: {e}")
        # Handle the error, skip the line or log it appropriately.
        continue

print("Translation complete.")

# Save the translated DataFrame to a new CSV file
df_translated.to_csv('embarrassment_data_id.csv', index=False)
print("Translated data saved to 'embarrassment_data_id.csv'")

---

In [ ]:
completeemlabel = pd.read_csv('/kaggle/input/combined-data-5304/combined_data.csv')
completeemlabel.info()

In [ ]:
import pandas as pd

# Assuming 'train_fearjealousy.tsv' is in the current directory
try:
    emolit = pd.read_csv('/kaggle/input/embarrassment-and-envy-labels/emolit/trn.tsv', sep='\t')  # Specify the separator as tab
except FileNotFoundError:
    print("Error: 'trn.tsv' not found.")
    exit()

# Convert the DataFrame to CSV
emolit.to_csv('/kaggle/working/emolit.csv', index=False)  # index=False prevents writing row indices
print("Conversion complete. File saved as 'emolit.csv'")

In [ ]:
emparttwo = pd.read_csv('/kaggle/working/emolit.csv')
emparttwo.info()

In [ ]:
import pandas as pd

# Load the dataset
emparttwo = pd.read_csv('/kaggle/working/emolit.csv')

# Keep only "embarrassment" and "envy" columns
emparttwo = emparttwo[['text','embarrassment', 'envy']]

# Display the first few rows
print(emparttwo.head())

# Save the cleaned dataset (optional)
emparttwo.to_csv('/kaggle/working/emolit_filtered.csv', index=False)

In [ ]:
# Drop rows where both "embarrassment" and "envy" are below 0.8
emparttwo_filtered = emparttwo[(emparttwo['embarrassment'] >= 0.8969) | (emparttwo['envy'] >= 0.8969)]

# Display the first few rows to verify
print(emparttwo_filtered.head())

# Save the filtered dataset (optional)
emparttwo_filtered.to_csv('/kaggle/working/emolit_filtered.csv', index=False)

In [ ]:
emparttwo_filtered.info()

In [ ]:
embarrassment_count = (emparttwo_filtered['embarrassment'] >= 0.8969).sum()
print("Rows with embarrassment ≥ 0.8969:", embarrassment_count)

envy_count = (emparttwo_filtered['envy'] >= 0.8969).sum()
print("Rows with envy ≥ 0.8969:", envy_count)

In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv('/kaggle/working/emolit_filtered.csv')

# Create two separate DataFrames
df_embarrassment = df[df['embarrassment'] > df['envy']]
df_envy = df[df['envy'] > df['embarrassment']]

# Save to separate CSV files
df_embarrassment.to_csv('/kaggle/working/emolit_embarrassment.csv', index=False)
df_envy.to_csv('/kaggle/working/emolit_envy.csv', index=False)

# Display confirmation
print("Files saved successfully:")
print(" - emolit_embarrassment.csv ->", len(df_embarrassment), "rows")
print(" - emolit_envy.csv ->", len(df_envy), "rows")

In [ ]:
emolit_em = pd.read_csv('/kaggle/working/emolit_embarrassment.csv')
emolit_em.head()

In [ ]:
emolit_em = pd.read_csv('/kaggle/working/emolit_embarrassment.csv')
emolit_em.head()

emolit_em = emolit_em.drop(columns=['envy'])  # Or: emolit_em.drop('envy', axis=1)

emolit_em.head() # Display the updated DataFrame

In [ ]:
emparttwo_emb = emolit_em[emolit_em['embarrassment'] >= 0.8969]

emparttwo_emb.info()

In [ ]:
emparttwo_emb.to_csv('/kaggle/working/emolit_embarrassment_en.csv', index=False)

In [ ]:
emolit_env = pd.read_csv('/kaggle/working/emolit_envy.csv')
emolit_env.head()

emolit_env = emolit_env.drop(columns=['embarrassment'])

emolit_env.head() # Display the updated DataFrame

In [ ]:
envydata = emolit_env[emolit_env['envy'] >= 0.8969]

envydata.info()

In [ ]:
envydata.to_csv('/kaggle/working/emolit_envy_en.csv', index=False)

---

In [ ]:
empttwo = pd.read_csv('/kaggle/input/last-i-hope/emolit_embarrassment_en.csv')
empttwo.info()

In [ ]:
empttwo = empttwo.drop(columns=['embarrassment'])

In [ ]:
empttwo.to_csv('textonly-emolit-em.csv', index=False)

---

In [ ]:
import pandas as pd

envydata = pd.read_csv('/kaggle/input/lastplz/emolit_envy_en.csv')
envydata.head()

In [ ]:
envydata = envydata.drop(columns=['envy'])

In [ ]:
envydata.head()

In [ ]:
envydata.to_csv('/kaggle/working/textonly-emolit-envy.csv', index=False)

---

In [ ]:
import pandas as pd

addid = pd.read_csv('/kaggle/input/add-random-id/combined_data_all_labels.csv')
addid.info()

In [ ]:
addid.head(6975)

In [ ]:
import pandas as pd
import numpy as np

# Load the dataset
addid = pd.read_csv('/kaggle/input/add-random-id/combined_data_all_labels.csv')

# Fill the ID column with unique sequential numbers
addid['ID'] = np.arange(1, len(addid) + 1)

# Shuffle the dataset while keeping text and labels aligned
addid = addid.sample(frac=1, random_state=42).reset_index(drop=True)  # Random seed for reproducibility

# Save the modified dataset
addid.to_csv('/kaggle/working/combined_data_shuffled.csv', index=False)

# Display confirmation
print("Shuffled dataset saved as combined_data_shuffled.csv with", len(addid), "rows.")

In [ ]:
combinedfinal = pd.read_csv('/kaggle/working/combined_data_shuffled.csv')
combinedfinal.info()

In [ ]:
combinedfinal.head(6975)

In [ ]:
# Count values in each column
for column in combinedfinal.columns:
    print(f"Value counts for column '{column}':")
    print(combinedfinal[column].value_counts())
    print("-" * 20)

---

**EDA dan Preprocessing**

---

In [ ]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset (modify path accordingly)
df = pd.read_csv('/kaggle/working/combined_data_shuffled.csv')

# Display first few rows
df.head()

In [ ]:
# Count how many times each emotion appears
emotion_counts = df.iloc[:, 2:].sum()

# Plot the distribution
plt.figure(figsize=(8,5))
sns.barplot(x=emotion_counts.index, y=emotion_counts.values, palette="viridis")
plt.title("Distribution of Emotion Labels")
plt.ylabel("Count")
plt.show()

In [ ]:
from wordcloud import WordCloud

# Combine all text into one string
text = " ".join(df["Teks"])

# Generate a word cloud
wordcloud = WordCloud(width=800, height=400, background_color="white").generate(text)

# Display the word cloud
plt.figure(figsize=(10,5))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.show()

In [ ]:
df["Teks"] = df["Teks"].str.lower()

In [ ]:
import re

df["Teks"] = df["Teks"].apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', x))

In [ ]:
from transformers import AutoTokenizer

# Load IndoBERT tokenizer
tokenizer = AutoTokenizer.from_pretrained("indolem/indobert-base-uncased")

# Tokenize the text column
df["Teks"] = df["Teks"].apply(lambda text: tokenizer.tokenize(text))

# Display result
print(df.head())

In [ ]:
# from nltk.corpus import stopwords

# nltk.download("stopwords")
# stop_words = set(stopwords.words("indonesian"))  # Use Indonesian stopwords

# df["Teks"] = df["Teks"].apply(lambda x: [word for word in x if word not in stop_words])

In [ ]:
df.head()

In [ ]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Convert tokenized text back to a single string for WordCloud
text = " ".join([" ".join(words) for words in df["Teks"]])

# Generate WordCloud
wordcloud = WordCloud(
    width=1000, height=500,
    background_color="white",
    colormap="viridis"
).generate(text)

# Display the WordCloud
plt.figure(figsize=(12, 6))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")  # Hide axes
plt.title("WordCloud of Cleaned Text Data", fontsize=14)
plt.show()

In [ ]:
# df.to_csv("/kaggle/working/cleaned_data_no_lemmatization.csv", index=False)
df.to_csv("/kaggle/working/cleaned_dataset_with_stopwords.csv", index=False)

---

**Pelatihan**

---

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# prompt: read /content/drive/MyDrive/Tugas Akhir/cleaned_dataset_with_stopwords.csv

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Tugas Akhir/cleaned_dataset_with_stopwords.csv')
df.head()

,ID,Teks,Senang,Sedih,Marah,Iri,Malu,Takut
0,2143,"['saya', 'merasa', 'sangat', 'anggun', 'sangat...",1,0,0,0,0,0
1,626,"['saya', 'mulai', 'tidak', 'percaya', 'bahwa',...",0,0,1,0,0,0
2,3711,"['untuk', 'kehilangan', 'teman', 'dekat', 'ata...",0,1,0,0,0,0
3,5121,"['ini', 'membuat', 'kaum', 'liberal', 'terliha...",0,0,0,0,1,0
4,469,"['i', 'mengatakan', 'menekan', 'tubuhnya', 'ke...",0,0,1,0,0,0

In [ ]:
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
import ast

# 1. Load Dataset
dataset_path = "/content/drive/MyDrive/Tugas Akhir/cleaned_dataset_with_stopwords.csv"
print("📥 Loading dataset...")
df = pd.read_csv(dataset_path)

# 2. Convert tokenized text back into readable sentences
print("🔄 Converting tokenized text back to sentences...")
df['Teks'] = df['Teks'].apply(ast.literal_eval)  # Convert string list to actual list
df['Teks'] = df['Teks'].apply(lambda x: ' '.join(x))  # Join tokens into a single string

# 3. Extract text and labels
print("📌 Extracting text and labels...")
texts = df['Teks'].tolist()
labels = df[['Senang', 'Sedih', 'Marah', 'Iri', 'Malu', 'Takut']].values

# 4. Split dataset into training and validation sets
print("✂️ Splitting dataset into training (80%) and validation (20%)...")
train_texts, val_texts, train_labels, val_labels = train_test_split(
    texts, labels, test_size=0.2, random_state=42
)

# 5. Load IndoBERT tokenizer
print("🔠 Loading IndoBERT tokenizer...")
tokenizer = BertTokenizer.from_pretrained("indobenchmark/indobert-base-p1")

# 6. Tokenization function
def tokenize_function(texts):
    return tokenizer(texts, padding=True, truncation=True, max_length=512, return_tensors='pt')

# 7. Define Dataset Class
class EmotionDataset(Dataset):
    def __init__(self, texts, labels):
        self.encodings = tokenize_function(texts)
        self.labels = torch.tensor(labels, dtype=torch.float)  # Multi-label classification

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item['labels'] = self.labels[idx]
        return item

# 8. Create dataset objects
print("📦 Creating PyTorch datasets...")
train_dataset = EmotionDataset(train_texts, train_labels)
val_dataset = EmotionDataset(val_texts, val_labels)

# 9. Load IndoBERT model for multi-label classification
print("🧠 Loading IndoBERT model...")
model = BertForSequenceClassification.from_pretrained(
    "indobenchmark/indobert-base-p1", num_labels=6, problem_type="multi_label_classification"
)

# 10. Define Training Arguments
print("⚙️ Setting up training arguments...")
training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=10,
    save_total_limit=2  # Keep only last 2 checkpoints
)

# 11. Initialize Trainer
print("🚀 Initializing Trainer...")
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

# 12. Train the Model
print("🎯 Starting training...")
trainer.train()

# 13. Save the Model and Tokenizer
print("💾 Saving model and tokenizer...")
model.save_pretrained("./indobert_emotion_model")
tokenizer.save_pretrained("./indobert_emotion_model")

print("✅ Training complete! Model saved in './indobert_emotion_model'")

📥 Loading dataset...
🔄 Converting tokenized text back to sentences...
📌 Extracting text and labels...
✂️ Splitting dataset into training (80%) and validation (20%)...
🔠 Loading IndoBERT tokenizer...

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/229k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

📦 Creating PyTorch datasets...
🧠 Loading IndoBERT model...

pytorch_model.bin:   0%|          | 0.00/498M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at indobenchmark/indobert-base-p1 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1594: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

⚙️ Setting up training arguments...
🚀 Initializing Trainer...

model.safetensors:   0%|          | 0.00/498M [00:00<?, ?B/s]

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.

🎯 Starting training...

wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: aqilakill (its-aqila) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

💾 Saving model and tokenizer...
✅ Training complete! Model saved in './indobert_emotion_model'

In [ ]:
# prompt: check accuracy etc of /content/indobert_emotion_model

from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# Assuming you have your trained model and tokenizer loaded
model = BertForSequenceClassification.from_pretrained("/content/indobert_emotion_model")
tokenizer = BertTokenizer.from_pretrained("/content/indobert_emotion_model")

# Load your validation dataset (replace with your actual dataset)
val_dataset = EmotionDataset(val_texts, val_labels)

# Function to predict labels for a given dataset
def predict_labels(dataset):
    predictions = []
    for batch in DataLoader(dataset, batch_size=8):
        inputs = {k: v.to(model.device) for k, v in batch.items() if k != 'labels'}
        outputs = model(**inputs)
        predicted_labels = (torch.sigmoid(outputs.logits) > 0.5).cpu().numpy().astype(int)
        predictions.extend(predicted_labels)
    return predictions

# Make predictions on the validation set
predicted_labels = predict_labels(val_dataset)

# Calculate accuracy, precision, recall, F1-score
accuracy = accuracy_score(val_labels, predicted_labels)
precision, recall, f1_score, _ = precision_recall_fscore_support(val_labels, predicted_labels, average='weighted')

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1_score:.4f}")

# You can also calculate per-class metrics if needed
# precision, recall, f1_score, _ = precision_recall_fscore_support(val_labels, predicted_labels, average=None)
# print("Per-class metrics:")
# for i in range(6):  # Assuming 6 emotion labels
#     print(f"Label {i}: Precision={precision[i]:.4f}, Recall={recall[i]:.4f}, F1-Score={f1_score[i]:.4f}")

Accuracy: 0.8731
Precision: 0.8850
Recall: 0.8781
F1-Score: 0.8814